YunoHost/moulinette

debian/control
locales/en.json
moulinette/__init__.py
moulinette/actionsmap.py
moulinette/authenticators/__init__.py
moulinette/interfaces/__init__.py
moulinette/interfaces/api.py
moulinette/interfaces/cli.py
moulinette/utils/log.py
moulinette/utils/stream.py

It aims to remove the *display* signals and replace it by the `logging` module. Thanks to some tweaks and configurations, it comes with at least the same features and also more, such as:
* join logging and messages display in one place to make it easier to control and use
* select what to log, when and where
* do not re-invent the wheel, the logging configuration is straight enough to be extended!
Note that it's still compatible with the old-and-soon-deprecated `msignals.display` function in order to facilitate merging and by the way tests.
It also come with some other features such as bash-completion - which still need to be activated per project.

Provide new logging facilities and other helpers

---

moulinette/actionsmap.py

For performance reasons I've chosen to use `actionmap.yml` file size as it is super fast to check.

[enh] automatically regenerate cache if actionmap.yml is modified

---

moulinette/actionsmap.py

Hello,
During installation the cache dir might not be present, it is created at this line using a magical helper https://github.com/YunoHost/moulinette/blob/54a50a40b9b678579041e5a8eee2b61e77536aac/moulinette/actionsmap.py#L538
This might that listing a non-existing dir raise an exception and break the installation. This bug is therefor *critical* and needs to be merged (or another solution) before we make a release.
This is a minor decision.

[fix] at installation the cache dir might not be present

---

moulinette/interfaces/cli.py

Hello,
This isn't a great solution but could avoid some bug: it increases the timeout of a cli command from 5 to 30 while we don't have a <code>--wait</code> option.
This is a small decision.

increase cli timeout

---

moulinette/utils/process.py

Hello,
This is a fix for this super long ticket https://dev.yunohost.org/issues/654. After (long) investigations by @maniackcrudelis, we end up finding that add a `time.sleep(1)` solves the issue on his testing environment.
This PR had a timeout mecanism to make this approach a bit more robust.
This bug is critical for our CI.
**I haven't tested this PR yet, I'm too tired for that and need to sleep for work.**

Unfinished process bug

---

moulinette/actionsmap.py

When trying to add an actionmap for `yunohost tools urlavailability domain path`, moulinette swapped the domain and path arguments (i.e. wanted to have `yunohost tools urlavailability path domain`) because of the way the cache is stored. This is pretty inconvenient because that's not a natural order for the argument.
I noticed that there were some inconsistency [here](https://github.com/YunoHost/moulinette/blob/6c200ad9c9ce889fe1e94497b9b9dbfcf9dc7f90/moulinette/actionsmap.py#L385-L399) between `pickle.load()` (unordered, "the default stuff") and `ordered_yaml_load()` (ordered, used in some weird cases ?). 
This is pretty nasty because right now we can't trust the order of the arguments requested/given ... i.e. if we have any command such as `yunohost category action arg1 arg2`, then …

Use ordered dict for the actionmap cache

---

moulinette/interfaces/__init__.py

Ready for reviews / feedback
This is a proposal to fix what's described in https://dev.yunohost.org/issues/867. The --help / usage shown for some commands is confusing and sometimes does not work as expected
```bash
$ yunohost app addaccess --help
usage: yunohost app addaccess [-h] [-u [USERS [USERS ...]]] apps [apps ...]
```
```bash
$ yunohost app addaccess -u some_user some_app
yunohost app addaccess: error: too few arguments
```
```bash
$ yunohost app addaccess some_app -u some_user
[works]
```
This is a bug / inconsistent behavior in `argparse`, discussed [here](http://stackoverflow.com/questions/5854920/argparse-incorrect-order-of-positional-and-optional-parameters), [here](http://bugs.python.org/issue9338) (2010 :sob:) and in other places
Digging into this, I don't understand the …

[fix] Show positional arguments first in --help / usage

---

locales/en.json
moulinette/utils/filesystem.py
moulinette/utils/network.py
moulinette/utils/process.py
moulinette/utils/tests/conftest.py
moulinette/utils/tests/test_filesystem.py
moulinette/utils/tests/test_network.py
moulinette/utils/tests/test_process.py

This is a continuation of https://github.com/YunoHost/yunohost/pull/274 as I realized that what I wanted to implement was already partly in the moulinette and it makes more sense to have them here as they are independent from Yunohost itself.
Here's the initial Problem/Solution description :
>### Problem
>
>Follow-up of a discussion we had two or three times already : we keep needing to read / write json files, change file permissions or downloading stuff at various places in the code. This lead to either duplicated code, or different pieces of code that don't handle exceptions consistently. The current situation also discourage to handle exceptions correctly because there are simply too many of them to check (e.g. when doing a `requests.get()`)
>
>### Proposed solution
>
>Introduce …

[enh] More helpers for common IO operations

---

moulinette/interfaces/api.py

At the moment, the moulinette does not properly handle exception when called with the API. This trigger an obscure "500 Internal Server Error" on the webadmin.
Add an exception handling and feed the web admin with the details/traceback of what happened.
Related PR on Moulinette : https://github.com/YunoHost/yunohost-admin/pull/166

[fix] Correctly handle error 500

---

moulinette/actionsmap.py
moulinette/interfaces/__init__.py
moulinette/interfaces/api.py
moulinette/interfaces/cli.py
moulinette/utils/filesystem.py
moulinette/utils/process.py

I recommend to read this commits by commits as a lot of things have been modified.
I've tried to make "one action per commit" to make the workflow more understandable.
If that's too much at once we can try to split into several batch of commits.
Normally I haven't break anything (yunohost-{cli,api} works for me with this refactoring in ynh-dev).
Still, it's not perfect, the code makes a lot way too much interconnections and is full of magic and "out of nowhere" stuff so we'll have to move step by step and this is a first one.
I'm still impressed by all the things that moulinette does, this isn't a trivial problem.

try to make ActionsMap._construct_parser code more readable

---

moulinette/interfaces/cli.py

Right now it's a bit frustrating that, when you forgot what a not-so-trivial command does, type `yunohost foo bar --help` but this doesn't tell you anything about what the command does ! To get the info, you need to run `yunohost foo --help` and read the help for argument `bar`.
Add a description field for categories, subcategories and actions.
Result :

[enh] Show description of command in --help

---

debian/control
moulinette/core.py
moulinette/interfaces/__init__.py
moulinette/interfaces/api.py

Commands like `yunohost service regen-conf` needs to indirectly call daughter `yunohost` commands (e.g. `yunohost domain list` in hooks for instance). However, the normal behavior in the moulinette is that you cannot run multiple `yunohost` commands at the same time (c.f. lock mechanism). Right now, commands that need to be able to call other `yunohost` commands in their hooks needs to have `lock: false` in the actionsmap (such that the daughters can take the lock). This can be seen as a bit counterintuitive and overcomplicated.
Before trying to acquire the lock, check if the parent or grand-parent or grand-grand-parent (and so on) has the lock. If so, ignore the lock mechanism.

[enh] Simpler lock system

---

moulinette/utils/network.py

For some requests (e.g. with the dynette, [here](https://github.com/YunoHost/dynette/blob/255e539322573feb22b8a6346e1ae54ec5bb7a9d/dynette.rb#L149-L156)), we can expect a return code != 200 even if there's not 'real' error with the request itself... 
Add a mechanism about an expected return code (200 by default) for `download_text/json`. Setting the expected return code to None ignores it.

[enh] Optional expected status code for `download_text/json`

---

moulinette/core.py

We want to be able to manage several locks. Also a command waiting to acquire the lock should keep checking if one of its parent got it in the meantime.
This is motivated by https://github.com/YunoHost/yunohost/pull/367
The lock file can now contain several lock (on separate lines) and keep checking in `acquire()` if one of its parent got the lock (instead of just once in `__enter__()`).

Allow to give lock to multiple processes

---

moulinette/actionsmap.py
moulinette/utils/network.py

While troubleshooting performance issues on yunohost I found out that some package imports were very slow and I think loading time is valuable information for debugging.
This PR makes this information visible when using `--debug` command line switch.
I also moved a slow import of module *requests*. Although I'm not sure this one currently improves perfs, it may be the case in the future.

[enh] Lazy-load some modules to improve performances

---

doc/utils/filesystem.rst
locales/en.json
moulinette/utils/filesystem.py

We often works with yaml in yunohost so this uniformize and simplify this job.
Also it uses `safe_load` everywhere because default load is not safe...

[enh] new utils to read yaml files

---

moulinette/utils/serialize.py

The date is send in python format, not good for a Web API
https://cloud.githubusercontent.com/assets/41827/16403714/5501e2a4-3cf8-11e6-8c2e-a77d57ab5a7f.png
Display the date correctly, in a usable format
This PR use date: https://github.com/YunoHost/yunohost/pull/165 
The webadmin PR associated is : https://github.com/YunoHost/yunohost-admin/pull/130

[fix] Display the date in a correct format

---

moulinette/core.py

Error:
```
Setting up yunohost (3.0.0.1+201806221219) ... 
Regenerating configuration, this might take a while... 
Traceback (most recent call last): 
File "/usr/bin/yunohost", line 213, in <module> 
timeout=opts.timeout, 
File "/usr/lib/python2.7/dist-packages/moulinette/__init__.py", line 136, in cli 
moulinette.run(args, output_as=output_as, password=password, timeout=timeout) 
File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/cli.py", line 390, in run 
ret = self.actionsmap.process(args, timeout=timeout) 
File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 471, in process 
with MoulinetteLock(namespace, timeout): 
File "/usr/lib/python2.7/dist-packages/moulinette/core.py", line 528, in __enter__ 
self.acquire() 
File …
```

[fix] sometime we get an empty string

---

moulinette/utils/process.py
moulinette/utils/stream.py

This is needed for the config-panel.
The problem that is solved is that the callback given to hook_exec were executed in another process, thus I couldn't modify the closure on the main process here https://github.com/YunoHost/yunohost/blob/165e9bc63d3d92ee9a6dcf244e95f848d212ea19/src/yunohost/app.py#L1471 https://github.com/YunoHost/yunohost/blob/165e9bc63d3d92ee9a6dcf244e95f848d212ea19/src/yunohost/app.py#L1477 since it was executed in another process.
To solve this, instead of switching everything to threads and maybe break things in a weird way, I've just put back the consumer responsible for calling the callbacks in the main process instead of putting it into a fork.
The resulting API is not especially pretty but that should do it. 
I've checked and this stream.py code is only …

[mod] execute async consumers in the main process

---

moulinette/core.py

Fix the describe situation here https://github.com/YunoHost/yunohost/pull/512#discussion_r207753553
Tested in yunohost-tools-shell.
```
In [1]: m18n.n('app_location_unavailable')
Out[1]: 'This url is not available or conflicts with the already installed app(s):\n{apps:s}'
```
For some reason warning won't appear in yunohost shell :C

Dont crash on failed to format translation string

---

moulinette/authenticators/ldap.py

https://forum.yunohost.org/t/warning-moulinette-authenticator-ldap/5189/5

[fix] Unapropriate warning

---

moulinette/actionsmap.py

Related to https://github.com/YunoHost/yunohost/pull/196, it would be nice from a UX point of view to inform the admin/user about the constrain on the password rather than coldly refusing a password after it has been given (probably cancelling the whole command, then the user needs to reanswer every argument)
More generally, there are several case where we might want to add a comment to clarify what is asked. For instance, during the postintall, it may be good to have a comment explaining what is the Main domain and that it can be changed later for instance.
Allow arguments in the actionmap to specify a string key corresponding to a comment that shall be displayed before asking the argument.
For instance, we may have : 
```
-n:
full: --new-password
extra:
password: ask_new_admin_password …
```

Allow to add comments to parameters

---

moulinette/actionsmap.py
moulinette/interfaces/__init__.py
moulinette/interfaces/api.py
moulinette/utils/filesystem.py
moulinette/utils/log.py
moulinette/utils/process.py

The Travis-CI build fails for coding style reasons (first occurence quickly found is build [#278](https://travis-ci.org/YunoHost/moulinette/builds/419280251)). Some modules import unnecessary symbols.
Fix coding style according to PEP8. Remove unused imports except for those explicitly marked as voluntary.
Changes to make the CI build work are trivial and in principle harmless. Removal of unused imports may break client code (that shouldn't be) relying on them. Didn't check thoroughly for module import side effects within the `moulinette` code itself but doesn't seem to be the case. Ready for review.

Fix coding style

---

moulinette/interfaces/api.py

I don't think it's any useful without Access-Control-Allow-Methods anyway.

Remove Access-Control-Allow-Origin

---

debian/control
moulinette/interfaces/cli.py
moulinette/utils/serialize.py

Dates are not well displayed. Currently it's just a str(date) and in some case yunohost give a timestamp... We need to harmonize that, and manage timezone.
Display dates using system timezone if we use cli.
Note: With the api, the json encoder already use iso format on the date object, so if the date is not "naive" date the representation generated by the api contains timezone info.
https://github.com/YunoHost/moulinette/blob/stretch-unstable/moulinette/utils/serialize.py#L30
Ready
This PR is linked to 
https://github.com/YunoHost/yunohost/pull/552

[enh] Display date as system timezone

---

moulinette/authenticators/ldap.py

- When we call the function `validate_uniqueness` we can't know if there are a conflict we don't know which attribute have generate a conflict and with which object we have a conflict.
- We can't manage the error with the function which call `validate_uniqueness`. Result is that if there are a conflict the user just see a message "Attribute '{attribute}' already exists with value '{value}'" but the user might not know the meaning of the attribute name.
- Create a function `get_conflict` which just return the name of the attribute and it value if there are a conflict.

Add possiblity to get attribute name of conflict in LDAP

---

locales/en.json
moulinette/__init__.py
moulinette/actionsmap.py
moulinette/authenticators/__init__.py
moulinette/authenticators/ldap.py
moulinette/core.py
moulinette/interfaces/__init__.py
moulinette/interfaces/api.py
moulinette/interfaces/cli.py
moulinette/utils/filesystem.py
moulinette/utils/network.py

The problem
Utilisation trop complexe. Fait perdre du temps de dev.
Solution
Supression des code d'erreur "errno et de l'internationalisation "m18n.n"
this PR depends of  https://github.com/YunoHost/yunohost/pull/574

[enh] Simplify moulinette errors

---

moulinette/authenticators/__init__.py

So, today somebody encountered this stupid issue where he could not login anymore to the webadmin.
Turns out that for some reasons moulinette uses gpg to encrypt some values in cache. The issue lies in the fact that if there's an error in `/root/.gnupg/gpg.conf` (such as a bad option), `gpg.encrypt()` will simply return an empty string...
With verbosity on (`gnupg.GPG(verbose=True)`), we were able to see : `gpg: /root/.gnupg/gpg.conf:2: invalid`. The user told me that he was using duply for backups which also relies on gpg, and that might be related.
Anyway, I propose to add an assertion to check this to be able to pinpoint the issue more easily when this happens...

Make sure `gpg.encrypt` actually does something

---

test/conftest.py

For documentation, see https://docs.pytest.org/en/latest/fixture.html#scope-sharing-a-fixture-instance-across-tests-in-a-class-module-or-session. I missed this on the last PR #203.

Invoke Pytest fixture options correctly

---

locales/en.json
moulinette/core.py

Today (and like in several other cases) I end up in front of a user convinced that their YunoHost was totally broken because they though that nothing worked anymore. I've suspected the lock directly but it was hard to debug because even `--debug` didn't informed that YunoHost was waiting for the lock.
So this PR add 2 mechanism to fix this:
* add a simple `logger.debug` line to tell that we are entering the lock mechanism
* add a gradual `logger.warning` mechanism to tell the user that we are waiting and still waiting for the other command to finish
My formulation for the second error message might not be very clear so if you have a better suggestion try to improve it please.
I'm also expecting those message to bring users try to understand what is happening and how to debug that, one …

Warn the user about long locks for a way better UX

---

.travis.yml
README.md
moulinette/interfaces/__init__.py
moulinette/interfaces/api.py
moulinette/interfaces/cli.py
moulinette/utils/log.py
setup.cfg
tox.ini

So, let's use Tox to run pycodestyle (new name for pep8) and run it in a parallel job.
Why? Well, I want to also start to introduce new jobs to Tox / Travis.
In the end, the developer experience will always be "just run pip install tox && tox"

Add lint job to Tox and Travis

---

moulinette/__init__.py
moulinette/actionsmap.py
moulinette/cache.py
moulinette/core.py
moulinette/globals.py
setup.py
test/test_cache.py

This follows the work on #203.
So, while trying to write more tests, I am running into the issue where I cannot mock the `moulinette.globals` configuration values. This makes it hard to control the environment for the unit tests more closely. This is because they are imported at package setup, initialised at package load and also imported globally at each module level.
So, I have tried in this change to refactor how these values are exposed. For consuming this library, I've introduced a new API, `moulinette.env` which allows you to do `moulinette.env['CACHE_DIR]` instead of `from moulinette import CACHE_DIR`. This is a breaking change but I haven't found any code in yunohost/yunohost that relies on these properties being exposed. Is there somewhere to look? Otherwise, internally, I've …

Refactor global loading

---

moulinette/actionsmap.py
test/test_actionsmap.py

Linking to https://github.com/YunoHost/issues/issues/1255 and https://github.com/YunoHost/issues/issues/1367.

Add tests to cover some part of actionsmap.py
